import "./global.css";
import TopNav from "./components/topNav";
import Footer from "./components/footer";
import MainContent from "./components/mainContent";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopNav></TopNav>
        <MainContent>{children}</MainContent>
        <Footer></Footer>
      </body>
    </html>
  );
}
