import TopNav from "./components/topNav";
import Footer from "./components/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopNav></TopNav>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
